### ISSUE TITLE
Cannot find module (userid)

### ISSUE THREAD

**Issue by iget-master** [patrikx3/ramdisk#1]
Hi, first I would like to say thanks about your package, I was looking how to do it for the same reason then you, using in IntelliJ (actually PHPStorm).

I've followed your installing instructions, but didn't worked. When I try to run the install command the following happens:

```
root@iget-esoares:/home/esoares/Sandbox# p3x-ramdisk install esoares
{ Error: Cannot find module '/home/esoares/.npm-global/lib/node_modules/p3x-ramdisk/node_modules/userid/build/Debug/userid.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/esoares/.npm-global/lib/node_modules/p3x-ramdisk/node_modules/userid/lib/userid.js:5:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
```
Node that it's trying to load the userid from the **Debug** build, that isn't available to me.

Running an LS on `/home/esoares/.npm-global/lib/node_modules/p3x-ramdisk/node_modules/userid/build` the directory `Debug` doesn't exists.

**Note:** Building from sources works OK!

**Comment by iget-master** [comment]
Hi, "build from sources", not a build actually, but cloning this repository and installing dependencies work fine just by following the README.md.

Looks like there are some difference between the "production" downloaded from `npm install` as the README suggests and cloning from repository.
